image: debian/sid
packages:
  - locales
  - git
  - shellcheck
  - xz-utils
tasks:
  - bashrc: |
      shellcheck hyperterm/.bash_profile
      shellcheck hyperterm/hyperterm/hyperterm.sh
      shellcheck hyperterm/hyperterm/_custom.sh
  - build: |
      shellcheck hyperterm/build.sh
      bash -x hyperterm/build.sh
  - core: |
      shellcheck hyperterm/hyperterm/core/autocomplete.sh
      shellcheck hyperterm/hyperterm/core/colors.sh
      shellcheck hyperterm/hyperterm/core/git.sh
      shellcheck hyperterm/hyperterm/core/languages.sh
      shellcheck hyperterm/hyperterm/core/status.sh
      shellcheck hyperterm/hyperterm/core/update.sh
  - themes: |
      shellcheck hyperterm/hyperterm/themes/default.sh
      shellcheck hyperterm/hyperterm/themes/joy.sh
      shellcheck hyperterm/hyperterm/themes/light_theme.sh
      shellcheck hyperterm/hyperterm/themes/minterm.sh
      shellcheck hyperterm/hyperterm/themes/pure.sh
      shellcheck hyperterm/hyperterm/themes/special.sh
  - tools: |
      shellcheck hyperterm/hyperterm/tools/aliases.sh
      shellcheck hyperterm/hyperterm/tools/compress.sh
      shellcheck hyperterm/hyperterm/tools/export.sh
      shellcheck hyperterm/hyperterm/tools/listuser.sh
      shellcheck hyperterm/hyperterm/tools/network.sh
      shellcheck hyperterm/hyperterm/tools/proxy.sh
      shellcheck hyperterm/hyperterm/tools/rar2zip.sh
      shellcheck hyperterm/hyperterm/tools/ruby.sh
      shellcheck hyperterm/hyperterm/tools/ssh-agent.sh
      shellcheck hyperterm/hyperterm/tools/sysinfo.sh
      shellcheck hyperterm/hyperterm/tools/virtualenv.sh
  - install: |
      shellcheck hyperterm/install.sh
      bash -x hyperterm/install.sh -s
  - uninstall: |
      shellcheck hyperterm/uninstall.sh
      bash -x hyperterm/uninstall.sh -s
  - shasums: |
      cd hyperterm
      cp -rv /hyperterm/ "$HOME/.hyperterm/"
      cp -v .bash* "$HOME"
      cp -v ./hyperterm/_custom.sh "$HOME"
      rm -rfv hyperterm/
      (cd "$HOME/.hyperterm/" && sha512sum -c hyperterm.sha512)
      (cd "$HOME" && bash -x .bashrc)
